name: MobDrop
main: com.brian.MobDrop.Main
version: 1.5.1
author: 0obrino0
website: www.youtube.com/user/brian041301
api-version: 1.13
depend: [SmartInvs]
commands:
   mobdrop:
      description: MobDrop Commands.
      aliases: mdop
      permission: MobDrop.player
      permission-message: you can not use it