name: MobDrop
main: com.brian.MobDrop.Main
version: 1.0.2
author: 0obrino0
website: www.youtube.com/user/brian041301
api-version: 1.13
commands:
   mobdrop:
      description: MobDrop Commands.
      permission: MobDrop.mobdrop
      permission-message: you can not use it